name = "analytics-api"
main = "src/index.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
workers_dev = false
route = "api.analytics.k-o.pro/*"

[vars]
FRONTEND_URL = "https://analytics.k-o.pro"
GOOGLE_CLIENT_ID = "724601444957-h1sofo90i307cjln4ds6jbdo601t314m.apps.googleusercontent.com"

# Replace with actual IDs
[[kv_namespaces]]
binding = "AUTH_STORE"
id = "64f21dad93ce4636bdc4daacd1f275bd"

[[d1_databases]]
binding = "DB"
database_name = "analytics-be"
database_id = "165cb9e2-49fb-40ee-b02d-58e2c5e072bb"

[observability]
enabled = true
head_sampling_rate = 1

[configuration]
cors = true

[[headers]]
pattern = "/*"
  [headers.response]
  Access-Control-Allow-Origin = "https://analytics.k-o.pro"
  Access-Control-Allow-Methods = "GET, POST, OPTIONS"
  Access-Control-Allow-Headers = "Content-Type, Authorization"
  Access-Control-Max-Age = "86400"