name = "analytics-api"
main = "src/index.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
workers_dev = false
route = "api.analytics.k-o.pro/*"

[vars]
FRONTEND_URL = "https://analytics.k-o.pro"
# These sensitive values should be set as environment variables
# GOOGLE_CLIENT_ID = ""
# JWT_SECRET = ""
# PASSWORD_SALT = ""
# GOOGLE_CLIENT_SECRET = ""

# Replace with actual IDs
[[kv_namespaces]]
binding = "AUTH_STORE"
id = "64f21dad93ce4636bdc4daacd1f275bd"

[[d1_databases]]
binding = "DB"
database_name = "analytics-be"
database_id = "165cb9e2-49fb-40ee-b02d-58e2c5e072bb"

[observability]
enabled = true
head_sampling_rate = 1