name = "analytics-api"
  main = "src/index.js"
  compatibility_date = "2025-03-01"

  [env.production]
  workers_dev = false
  route = "api.analytics.k-o.pro/*"

  [env.staging]
  workers_dev = true

  [vars]
  ENVIRONMENT = "production"
  OPENAI_API_URL = "https://api.openai.com/v1/chat/completions"
  FRONTEND_URL = "https://analytics.k-o.pro"

  # Add KV binding for token storage
  [[kv_namespaces]]
  binding = "AUTH_STORE"
  id = "your-kv-namespace-id" # Replace with actual value
  preview_id = "your-preview-kv-namespace-id" # Replace with actual value

  # Add D1 database binding
  [[d1_databases]]
  binding = "DB"
  database_name = "search_analytics_db"
  database_id = "your-d1-database-id" # Replace with actual value

  [triggers]
  crons = ["0 0 * * *"] # Daily cron job for data refresh