name = "analytics-api"
  main = "src/index.js"
  compatibility_date = "2025-03-01"

  [env.production]
  workers_dev = false
  route = "api.analytics.k-o.pro/*"

  [vars]
  FRONTEND_URL = "https://analytics.k-o.pro"

  # Replace with actual IDs
  [[kv_namespaces]]
  binding = "AUTH_STORE"
  id = "your-actual-kv-id"

  [[d1_databases]]
  binding = "DB"
  database_name = "search_analytics_db"
  database_id = "your-actual-d1-id"
  3. Setup GitHub Action:
  Create .github/workflows/deploy.yml:
  name: Deploy
  on:
    push:
      branches: [main]
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: cloudflare/wrangler-action@v3
          with:
            apiToken: ${{ secrets.CF_API_TOKEN }}
            accountId: ${{ secrets.CF_ACCOUNT_ID }}
            command: deploy --env production
          env:
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}